from . import zperiod
from . import zbank
from . import hr_afp
from . import family
from . import zemployee_extension
from . import hr_employee
from . import hr_contract
from . import hr_payslip
from . import zpayroll_closing
from . import hr_salary_rule