{
    "name": "Planilla Extendida Perú - MSTECH",
    "version": "1.0.0",
    "summary": "Extensión de Planilla RRHH compatible con normativa peruana",
    "category": "Human Resources",
    "author": "MSTECH Solutions",
    "depends": [
        #"hr", "hr_contract", "hr_payroll", "hr_work_entry",  #->hr_payroll es enterprise
        "hr_payroll_community",
        "hr_attendance",
        "hr_work_entry_holidays",
        "mstech_code_executor",
        "base_automation",
    ],
    "data": [
        "security/ir.model.access.csv",
        
        "data/hr_afp_data.xml",
        "data/hr_afp_rate_data.xml",
        "data/work_entry_types.xml",
        "data/hr_salary_rule_data.xml",
        "data/hr_payroll_structure_data.xml",
        "data/resource_calendar_data.xml",
        "data/pe_economic_activity_data.xml",
        "data/hr_rule_parameter_data.xml",
        "data/hr_contract_type_data.xml",
        "data/hr_holidays_public_data.xml",
        "data/hr_labor_regime_data.xml",
        "data/hr_plame_suspension_type_data.xml",
        "data/hr_leave_type_data.xml",
        "data/absence_cron.xml",
        "data/bonus_cron.xml",
        "data/vacation_cron.xml",
        "data/ir_sequence_data.xml",
        "data/python_code_execute_data.xml",
        "data/hr_report_template_data.xml",
        "data/hr_educational_situation_data.xml",
        "data/hr_job_occupation_data.xml",
        "data/hr_formative_modality_data.xml",
        
        "views/hr_employee_declaracion_5ta_pe_views.xml",
        "views/hr_employee_family_pe_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_contract_views.xml",
        "views/res_company_views.xml",
        "views/hr_work_entry_type_views.xml",
        "views/hr_bonus_config_views.xml",
        "views/hr_bonus_views.xml",
        "views/hr_commission_config_views.xml",
        "views/hr_commission_views.xml",
        "views/hr_attendance_views.xml",
        "views/hr_leave_views.xml",
        "views/hr_overtime_request_views.xml",
        "views/hr_labor_regime_pe_views.xml",
        "views/hr_plame_suspension_type_views.xml",
        "views/pe_economic_activity_views.xml",
        "views/hr_afp_rate_views.xml",
        "views/hr_leave_type_views.xml",
        "views/hr_rule_parameter_views.xml",
        "views/hr_payslip_analytic_cost_views.xml",
        "views/hr_payroll_structure_views.xml",
        "views/hr_payslip_run_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_report_file_views.xml",
        "views/hr_report_template_line_views.xml",
        "views/hr_report_template_views.xml",
        "views/res_bank_views.xml",
        "views/hr_contract_type_views.xml",
        "views/attendance_import_views.xml",
        "views/hr_salary_rule_views.xml",
        "views/menus.xml",
    ],
    'images': ['static/description/icon.png'],
    "cloc_exclude": [
        "data/*.xml",
    ],
    "installable": True,
    "application": True,
    "license": "Other proprietary",
}
