# -*- coding: utf-8 -*-

from . import hr_work_entry
from . import pe_economic_activity
from . import hr_job_occupation
from . import hr_educational_situation
from . import hr_formative_modality
from . import hr_payslip_worked_days
from . import company
from . import employee
from . import hr_contract_type
from . import contract
from . import overtime_request
from . import report_template
from . import report_file
from . import res_bank
from . import work_entry_type
from . import hr_payroll_structure
from . import payslip_analytic_cost
from . import payslip_run
from . import payslip
from . import hr_leave_type
from . import hr_leave
from . import hr_attendance
from . import bonus_config
from . import bonus
from . import commission_config
from . import commission
from . import plame_suspension_type
from . import hr_rule_parameter
from . import hr_afp_rate
from . import attendance_import
from . import hr_salary_rule
from . import hr_payslip_line
