# -*- coding: utf-8 -*-
from odoo import api, models
from odoo.tools.misc import format_date


class ReportBoletaPago(models.AbstractModel):
    _name = 'report.zpayroll.report_boleta_pago_document'
    _description = 'Reporte Boleta de Pago'

    ## Relaciona y obtiene datos desde el modelo zemployee_extension
    def _get_employee_extension(self, employee):
       
        if not employee:
            return False

        return self.env['zemployee.extension'].sudo().search([
            ('employee_id', '=', employee.id)
        ], limit=1)



    def _get_selection_label(self, record, field_name):
        """
        Devuelve la etiqueta visible de un campo selection.
        Ejemplo: 'essalud_regular' -> 'ESSALUD REGULAR'
        """
        if not record or not field_name:
            return ''

        field = record._fields.get(field_name)
        if not field or not getattr(field, 'selection', False):
            return ''

        value = record[field_name]
        if not value:
            return ''

        return dict(field.selection).get(value, '')

    ## Obtiene datos de hr.payslip
    def _get_period_data(self, payslip):
        
        month_name = ''

        if payslip.payroll_month:
            month_name = dict(
                payslip._fields['payroll_month'].selection
            ).get(payslip.payroll_month, '')

        year = payslip.payroll_year or ''

        return {
            'month_name': month_name,
            'year': year,
            'period_name': '%s - %s' % (month_name, year) if month_name or year else '',
        }



    ##data para la estructura de la boelta
    def _get_employee_data(self, payslip):
        employee = payslip.employee_id
        contract = payslip.contract_id
        company = payslip.company_id
        emp_ext = self._get_employee_extension(employee)

        return {
            # Empresa
            'company_name': company.name or '',
            'company_vat': company.vat or '',

            # Código / contrato
            'contract_code': contract.code if contract and contract.code else '',
            'employee_code': employee.barcode or employee.id or '',

            # Trabajador
            'name': employee.name or '',
            'gender': employee.gender or '',
            'birthday': format_date(self.env, employee.birthday) if employee.birthday else '',
            'identification_id': employee.identification_id or '',
            'nationality': employee.country_id.name or '',

            # Fechas laborales desde zemployee.extension
            'entry_date': format_date(self.env, emp_ext.entry_date) if emp_ext and emp_ext.entry_date else '',
            'termination_date': format_date(self.env, emp_ext.termination_date) if emp_ext and emp_ext.termination_date else '',

            # Contrato
            'job': employee.job_id.name or '',
            'wage': contract.wage if contract else 0.0,
            'contract_type': contract.contract_type_id.name if contract and contract.contract_type_id else '',
            #'cost_center': contract.analytic_account_id.name if contract and contract.analytic_account_id else '',
            'special_situation': 'Ninguna',

            # Extensión peruana
            'essalud_autogenerated': '',
            'cuspp': emp_ext.cuspp if emp_ext else '',
            'afp': emp_ext.afp_id.name if emp_ext and emp_ext.afp_id else '',
            'pension_scheme': self._get_selection_label(emp_ext, 'pe_pension_scheme') if emp_ext else '',
            'health_scheme': self._get_selection_label(emp_ext, 'pe_health_scheme') if emp_ext else '',

            # Dirección
            'address': employee.private_street or '',
            'address2': employee.private_street2 or '',
            
            # Licencias / vacaciones para boleta
            'leave_type': '',
            'leave_start_date': '',
            'leave_end_date': '',
        }




    ################## coneptos de la nomina
    # Primera parte para los coneptos de nomina, revisa el cdoigo
    def _get_lines_by_codes(self, payslip, codes):
        if isinstance(codes, str):
            codes = [codes]

        return payslip.line_ids.filtered(lambda line: line.code in codes)

    # Sgunda, suma los motos totales para cada concpeto
    def _sum_line_codes(self, payslip, codes, absolute=False):
        lines = self._get_lines_by_codes(payslip, codes)
        amount = sum(lines.mapped('total')) or 0.0

        if absolute:
            amount = abs(amount)

        return amount


    def _get_concept(self, payslip, codes, name, section='earning', show_zero=False, qty_label=''):
        amount = self._sum_line_codes(
            payslip,
            codes,
            absolute=True if section == 'deduction' else False
        )

        currency = payslip.company_id.currency_id

        if not show_zero and currency.is_zero(amount):
            return False

        return {
            'name': name,
            'amount': amount,
            'qty_label': qty_label or '',
            'section': section,
        }


    ## Metodo pra obtneer las ganancias del empleado que apareceran en la nomina
    def _get_earnings(self, payslip):
        earnings_config = [
            {
                'codes': ['BASIC'],
                'name': 'Sueldo Básico',
                'show_zero': True,
                'qty_label': '',
            },
            {
                'codes': ['ASIG_FAMILIAR'],
                'name': 'Asignación Familiar',
                'show_zero': False,
                'qty_label': '',
            },
            {
                'codes': ['hrs_25', 'hrs_35', 'hrs_100', 'hrs_200'],
                'name': 'Horas Extras',
                'show_zero': False,
                'qty_label': '',
            },
            {
                'codes': ['CLASES'],
                'name': 'Clases',
                'show_zero': False,
                'qty_label': '',
            },
            {
                'codes': ['COMISION'],
                'name': 'Comisión Ventas',
                'show_zero': False,
                'qty_label': '',
            },
            {
                'codes': ['BONO'],
                'name': 'Bonificación',
                'show_zero': False,
                'qty_label': '',
            },
            {
                'codes': ['VAC'],
                'name': 'Vacaciones',
                'show_zero': False,
                'qty_label': '',
            },
        ]

        earnings = []

        for item in earnings_config:
            concept = self._get_concept(
                payslip,
                item['codes'],
                item['name'],
                section='earning',
                show_zero=item.get('show_zero', False),
                qty_label=item.get('qty_label', ''),
            )

            if concept:
                earnings.append(concept)

        return earnings


    #### DEscuentos
    def _get_deductions(self, payslip):
        deductions_config = [
            {
                'codes': ['ONP', 'SNP'],
                'name': 'SNP',
                'show_zero': False,
            },
            {
                'codes': ['AFP-FONDO'],
                'name': 'Fondo de Pensiones AFP',
                'show_zero': False,
            },
            {
                'codes': ['AFP-SEGURO'],
                'name': 'Seguro Inv. AFP',
                'show_zero': False,
            },
            {
                'codes': ['AFP-COMISION'],
                'name': 'Comis. Porc. AFP',
                'show_zero': False,
            },
            {
                'codes': ['R5_RET'],
                'name': 'Renta 5ta Categoría',
                'show_zero': False,
            },
            {
                'codes': ['TARDE'],
                'name': 'Tardanzas',
                'show_zero': False,
            },
            {
                'codes': ['ADELANTO'],
                'name': 'Adelanto',
                'show_zero': False,
            },
            {
                'codes': ['EPS'],
                'name': 'E.P.S.',
                'show_zero': False,
            },
            {
                'codes': ['PRESTAMO'],
                'name': 'Préstamos al Personal',
                'show_zero': False,
            },
            {
                'codes': ['Desc_OTROS'],
                'name': 'Otros Descuentos',
                'show_zero': False,
            },
        ]

        deductions = []

        for item in deductions_config:
            concept = self._get_concept(
                payslip,
                item['codes'],
                item['name'],
                section='deduction',
                show_zero=item.get('show_zero', False),
                qty_label='',
            )

            if concept:
                deductions.append(concept)

        return deductions

    def _get_employer_contributions(self, payslip):
        """
        Aportaciones patronales para la boleta.
        Ajusta los códigos según tus reglas reales.
        """
        return {
            'sctr': self._sum_line_codes(payslip, ['SCTR', 'APORTE_SCTR']),
            'essalud': self._sum_line_codes(payslip, ['APORTE_ESSALUD', 'ESSALUD']),
            'senati': self._sum_line_codes(payslip, ['SENATI', 'APORTE_SENATI']),
            'eps': self._sum_line_codes(payslip, ['EPS', 'APORTE_EPS']),
        }


    def _get_totals(self, payslip, earnings, deductions):
        """
        Totales principales de la boleta.
        Prioriza líneas oficiales GROSS y NET.
        """
        currency = payslip.company_id.currency_id

        total_earnings = self._sum_line_codes(payslip, ['GROSS'])
        net_amount = self._sum_line_codes(payslip, ['NET'])

        if currency.is_zero(total_earnings):
            total_earnings = sum(item['amount'] for item in earnings)

        total_deductions_from_concepts = sum(item['amount'] for item in deductions)

        if not currency.is_zero(total_earnings) and not currency.is_zero(net_amount):
            total_deductions = total_earnings - net_amount
        else:
            total_deductions = total_deductions_from_concepts

        if currency.is_zero(net_amount):
            net_amount = total_earnings - total_deductions

        return {
            'total_earnings': total_earnings,
            'total_deductions': abs(total_deductions),
            'net_amount': net_amount,
        }


    ### MOdelo Secunadrio principal para alimentar de datos a la nomina
    def _get_report_data(self, payslip):
        earnings = self._get_earnings(payslip)
        deductions = self._get_deductions(payslip)
        employer_contributions = self._get_employer_contributions(payslip)
        totals = self._get_totals(payslip, earnings, deductions)

        return {
            'employee': self._get_employee_data(payslip),
            'period': self._get_period_data(payslip),
            'earnings': earnings,
            'deductions': deductions,
            'employer_contributions': employer_contributions,
            'totals': totals,
        }

    #MAIN
    @api.model
    def _get_report_values(self, docids, data=None):
        """
        Método principal que Odoo llama cuando genera el PDF.
        """
        docs = self.env['hr.payslip'].browse(docids)

        report_data_by_id = {}

        for payslip in docs:
            report_data_by_id[payslip.id] = self._get_report_data(payslip)

        return {
            'doc_ids': docids,
            'doc_model': 'hr.payslip',
            'docs': docs,
            'report_data_by_id': report_data_by_id,
        }